### PR TITLE
Use yaml unmarshaller instead of json's

### PR DESCRIPTION
**Pull request by jotak**
## Description

- This works without changing the input as YAML is a superset of JSON
- This allows to get rid of our prometheus model override, which was due to a bug when using JSON unmarshaller
- Refactor / simplify tests and confgen, doing less of the decode/reencode magic

## Dependencies

n/a

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [ ] Will this change affect NetObserv / Network Observability operator? If not, you can ignore the rest of this checklist.
* [ ] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [ ] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Comment by jotak** [comment]
Attempt fails, cf https://github.com/netobserv/flowlogs-pipeline/pull/623
We'd need to get rid of viper if we want to use yaml rather than json. I don't think viper brings anything super useful here, anyway.

**Comment by KalmanMeth** [comment]
@eranra I think viper was originally used to allow passing in command line configuration parameters. We need to decide whether we still need this.

**Comment by jotak** [comment]
@KalmanMeth yes it allows using various sources for parameters, but comes with this limitation of not being case sensitive which is annoying for yaml. Do you have any idea if the other parameter sources (such as ENV or command line) are actually used out in the wild?

**Comment by eranra** [comment]
> @KalmanMeth yes it allows using various sources for parameters, but comes with this limitation of not being case sensitive which is annoying for yaml. Do you have any idea if the other parameter sources (such as ENV or command line) are actually used out in the wild?

@jotak @KalmanMeth In past projects we used cobra https://github.com/spf13/cobra - I do not know if this is better in compared with viper. In any event, I think that for the completeness and simplicity of a "stand-alone" tool such as FLP it does make sense to keep the option to provide command-line parameters

**Pull request closed without merging**
