### PR TITLE
made encode a terminal stage

### PR DESCRIPTION
**Pull request by KalmanMeth**
Made encode_prom (and other encode stages) into a terminal stage.
We then do not need to add write_none as a dummy terminal stage.

### CODE REVIEW

**Comment by mariomac** [comment]
Temporarily setting do-not-merge label since this is a breaking change that can break existing installations and RC release.

Let me work on a temporary solution to keep NOO working after we merge this change.

**Comment by mariomac** [comment]
Please let's coordinate merging this PR at the same time as: https://github.com/netobserv/network-observability-operator/pull/93

**Comment by mariomac** [comment]
Unblocking the PR, after internally discussing and make sure that this won't break the next NOO release.

**Review by mariomac — APPROVED** [review]

**Comment by KalmanMeth** [comment]
@mariomac Mario, Please merge this PR at the same time you perform the merge on [https://github.com/netobserv/network-observability-operator/pull/93](url)

**Pull request merged**
