### PR TITLE
NETOBSERV-934: Add icmpv4/v6 bits to FLP

### PR DESCRIPTION
**Pull request by msherif1234**
https://github.com/netobserv/netobserv-ebpf-agent/pull/103 added support to ICMPv4/6 and updated gRPC protobuf this PR to syncup flb repo with those changes and update the unit-test cases.

Also gRPC connect api was changed recently to fix ipv6 socket so fixed its use in pipeline_test

### CODE REVIEW

**Comment by jotak** [comment]
/hold
need to coordinate with QE/doc

**Review by jpinsonneau — APPROVED** [review]
LGTM, thanks @msherif1234 :+1:

**Review by ronensc — APPROVED** [review]
LGTM

**Pull request merged**
