### PR TITLE
NETOBSERV-1197: Generalize TCPDrop to support more protocols

### PR DESCRIPTION
**Pull request by msherif1234**
https://github.com/netobserv/netobserv-ebpf-agent/pull/152 needs to be merged 1st then update netobserv-agent with the commit id

### CODE REVIEW

**Comment by dushyantbehl** [comment]
Seems just a rename /lgtm

**Comment by dushyantbehl** [comment]
@msherif1234 seems okay but there is a WIP tag with the PR heading.

**Comment by msherif1234** [comment]
> @msherif1234 seems okay but there is a WIP tag with the PR heading.

Thanks @dushyantbehl yeah it need to be updated with ebpf PR commit id

**Pull request merged**
