### PR TITLE
NETOBSERV-1352 enhance prom filters for RTT metrics

### PR DESCRIPTION
**Pull request by jpinsonneau**
This PR improve prom metrics filtering introducing:
- [x] `!nil` to match presenceof the field with any value
- [X] `nil` to match absence of the field
- [x] `|` splitter to match at least one value

### CODE REVIEW

**Review by jotak — APPROVED** [review]
LGTM

**Comment by jotak** [comment]
@jpinsonneau I flagged LGTM, but taken in the light of bug https://issues.redhat.com/browse/NETOBSERV-1344, we will need to have filters such as "FlowDirection==1 OR FlowDirection==2" and/or "FlowDirection!=0" and/or "FlowDirection~=1|2" ... we should probably think about that before merging

**Comment by jpinsonneau** [comment]
> @jpinsonneau I flagged LGTM, but taken in the light of bug https://issues.redhat.com/browse/NETOBSERV-1344, we will need to have filters such as "FlowDirection==1 OR FlowDirection==2" and/or "FlowDirection!=0" and/or "FlowDirection~=1|2" ... we should probably think about that before merging

Let's just merge all metrics PRs pending before doing the fix everywhere so we don't miss any ?

**Comment by jotak** [comment]
I'm ok to go with it but just to mention a small concern, it creates some reserved words or characters that are not possible to have in filters as raw text .. even if today it sounds unlikely to have "nil" or "|" actually written in a field and to be willing to filter on that (as a text value), still we are creating reserved keyword that we could avoid by just changing the API.

E.g: as an alternative, we could implement a `type` param on filters, as an enum: `exact` (= current behaviour), `presence`, `absence`, `regex`.
wdyt? we could do that as a follow-up

**Comment by jpinsonneau** [comment]
> I'm ok to go with it but just to mention a small concern, it creates some reserved words or characters that are not possible to have in filters as raw text .. even if today it sounds unlikely to have "nil" or "|" actually written in a field and to be willing to filter on that (as a text value), still we are creating reserved keyword that we could avoid by just changing the API.
> 
> E.g: as an alternative, we could implement a `type` param on filters, as an enum: `exact` (= current behaviour), `presence`, `absence`, `regex`. wdyt? we could do that as a follow-up

As you prefer. I don't have strong opinion on that. Feel free to merge if it's blocking other PRs else I can refactor here; just let me know.

**Comment by jotak** [comment]
/approve
(this is blocking other PRs)

**Pull request merged**
